### ISSUE TITLE
[Feature] ability to choose a custom check interval

### ISSUE THREAD

**Issue by GuilloOme** [franglais125/update-extensions#1]
Would be nice to have a panel where we can choose a custom check interval, like "every week, one a day, twice a day, every hour,…)

**Comment by franglais125** [comment]
Indeed, thanks! I'll try to add something like this when I find the time.

**Comment by franglais125** [comment]
Hi, this was implemented here [053c64a9f1f6417ef3ddd3f4cd344d3726cbd8f1].

Cheers

**Comment by GuilloOme** [comment]
Thank you!
I updated the extension on two of my system but I can't see any "preferences" button on any of them.
I tried to reinstall it without success.

**Comment by franglais125** [comment]
Did you install it from extensions.gnome.org? If so, then you'll have to wait a bit more, as it's under review. I'll let you know when it gets approved (or you'll probably receive a notification saying the extensions has an update).

If you know what you are doing, you can install from github directly:
```
git clone https://github.com/franglais125/update-extensions
cd update-extensions
make install
```
And restart the Shell.

**Comment by GuilloOme** [comment]
ok, I'll be patient… and wais for the notification :smile: 

Thanks again for the update!
