### ISSUE TITLE
Show tray icon?

### ISSUE THREAD

**Issue by orschiro** [franglais125/update-extensions#13]
What a great and useful extension! 

Request:

Can we show a tray icon when updates are available?

The current notification OSDs are great but only if you see them while being in front of the computer. 

An additional tray icon would help to be notified in case you have missed the OSD. 

Yes, you can check the menu but I at least tend to forget about missed notifications in the menu.

**Comment by franglais125** [comment]
Hi! Thanks a lot for your interest in this extension.

I don't know if you are aware, but the chrome-gnome-shell extension (needed to install extensions from gnome.org) already has the update notifications functionality.

Mainly for this reason I haven't been working on this extension much; I usually spend more of my time on the apt-update-indicator and dash-to-dock development.

This being said, I'm open to PRs, or I may eventually work on this when I find some more time, sorry about that!

Thanks again, Fran

**Comment by orschiro** [comment]
Dear @franglais125,

I didn't know that, thanks!

I guess you're referring to this extension?

https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep

**Comment by franglais125** [comment]
Exactly, it is also available for Firefox.

**Comment by orschiro** [comment]
Thanks! I guess we can close this one then. :-)
