### ISSUE TITLE
Message body too large - check fails

### ISSUE THREAD

**Issue by jderose9** [franglais125/update-extensions#2]
I'm not actually able to get this extension working.

The problem seems to be that the server is denying the request due to the message body being too large. The entire metadata for the extension is passed in the request for updates - is that necessary? Can the extension UUID and Version be passed only (without the description)? Otherwise, maybe the batch size should be decreased to improve chances of the metadata fitting under the server limit.

Here's the message body:
`{"TaskBar@zpydr":{"_generated":"Generated by SweetTooth, do not edit","description":"TaskBar displays icons of running applications on the top panel or alternatively on a new bottom panel. Activate, minimize or close tasks with a simple click.\nTaskBar is a dock-like windows list on the top/bottom bar.\n\nOptions:\nDesktop button - toggle desktop view\nWorkspace button - switch workspaces left/right-click: cycle forward/backwards\nAppview button - left/right-click: toggle appview/overview\nFavorites - add from dash\nAlign position\nResize panels + adjust icon, label and content sizes\nTop/bottom panel background color + opacity\nBottom panel tray button - activate the message tray\nTasks on all workspaces\nTasks label\nTasks application menu\nClose tasks with a right/middle click\nActivate tasks on hover\nScroll tasks/workspaces\nSeparators\nThumbnail/label-preview\nPreview color + opacity\nColor or hide menu buttons\nDisable hot corner\n\nVersion 53 for GNOME 3.10 - 3.22\nzpydr@openmailbox.org\n\nLanguage support:\nChinese by wsxy162\nCzech by michal-ruzicka\nFrench by narzb\nGerman by jonnius\nSpanish by Testoriano\n\nCredit to Xes, flubshi, rogst, Baltix, boennhoff, skoslowski, rgeary1, hkskoglund, michal-ruzicka, skochxxl, tuhaihe, to-ba, tobimensch","name":"TaskBar","shell-version":["3.10","3.12","3.14","3.16","3.18","3.20","3.22","3.24"],"url":"https://github.com/zpydr/gnome-shell-extension-taskbar","uuid":"TaskBar@zpydr","version":53},"drive-menu@gnome-shell-extensions.gcampax.github.com":{"_generated":"Generated by SweetTooth, do not edit","description":"A status menu for accessing and unmounting removable devices.","extension-id":"drive-menu","gettext-domain":"gnome-shell-extensions","name":"Removable Drive Menu","settings-schema":"org.gnome.shell.extensions.drive-menu","shell-version":["3.22"],"url":"http://git.gnome.org/gnome-shell-extensions","uuid":"drive-menu@gnome-shell-extensions.gcampax.github.com","version":32},"impatience@gfxmonk.net":{"_generated":"Generated by SweetTooth, do not edit","description":"Speed up the gnome-shell animation speed","name":"Impatience","shell-version":["3.4","3.6","3.8","3.10","3.12","3.14","3.16","3.18","3.20","3.22"],"url":"http://gfxmonk.net/dist/0install/gnome-shell-impatience.xml","uuid":"impatience@gfxmonk.net","version":14},"dash-to-dock@micxgx.gmail.com":{"_generated":"Generated by SweetTooth, do not edit","description":"A dock for the Gnome Shell. This extension moves the dash out of the overview transforming it in a dock for an easier launching of applications and a faster switching between windows and desktops. Side and bottom placement options are available.","gettext-domain":"dashtodock","name":"Dash to Dock","original-author":"micxgx@gmail.com","shell-version":["3.18","3.20","3.22"],"url":"https://micheleg.github.io/dash-to-dock/","uuid":"dash-to-dock@micxgx.gmail.com","version":55},"drop-down-terminal@gs-extensions.zzrough.org":{"id":"drop-down-terminal","uuid":"drop-down-terminal@gs-extensions.zzrough.org","name":"Drop Down Terminal","description":"Drop down terminal toggled by a keystroke (the key above tab by default) for advanced users.","shell-version":["3.14","3.16","3.18","3.19.91","3.19.92","3.20","3.21.1","3.21.2","3.21.3","3.21.4"],"url":"https://github.com/zzrough/gs-extensions-drop-down-terminal","version":1},"bottompanel@tmoer93":{"_generated":"Generated by SweetTooth, do not edit","description":"Moves the GNOME panel to the bottom of the screen\nPlease report issues here: https://github.com/Thoma5/gnome-shell-extension-bottompanel","name":"BottomPanel","shell-version":["3.16","3.18","3.20","3.22"],"url":"","uuid":"bottompanel@tmoer93","version":8},"hide-dash@xenatt.github.com":{"_generated":"Generated by SweetTooth, do not edit","description":"Hide the dash from the activities overview.","name":"Hide Dash X","original-author":"zacbarton","shell-version":["3.10","3.12","3.14","3.16","3.18","3.20","3.22"],"url":"https://github.com/Edenhofer/Minimalism-Gnome-Shell","uuid":"hide-dash@xenatt.github.com","version":8},"openweather-extension@jenslody.de":{"_generated":"Generated by SweetTooth, do not edit","description":"Weather extension to display weather information from https://openweathermap.org/ or https://darksky.net for almost all locations in the world.\nFor openweathermap.org, you can either use the extensions default-key or register at http://openweathermap.org/appid and set the appropriate switch in the preferences dialog to \"off\".\nFor Dark Sky you have to register at https://darksky.net/dev/register and get a personal API-key.\n\nSince version 29 this extensions uses coordinates to store the locations and makes the names editable to support multiple weather-providers!\nIf you update from versions prior to 29 to 29 or greater (with darksky.net - support) you have to recreate your locations.","localedir":"/usr/local/share/locale","name":"OpenWeather","shell-version":["3.8","3.10","3.12","3.14","3.16","3.18","3.20","3.22"],"url":"https://github.com/jenslody/gnome-shell-extension-openweather","uuid":"openweather-extension@jenslody.de","version":78},"workspace-indicator@gnome-shell-extensions.gcampax.github.com":{"_generated":"Generated by SweetTooth, do not edit","description":"Put an indicator on the panel signaling in which workspace you are, and give you the possibility of switching to another one.","extension-id":"workspace-indicator","gettext-domain":"gnome-shell-extensions","name":"Workspace Indicator","original-authors":["erick.red@gmail.com"],"settings-schema":"org.gnome.shell.extensions.workspace-indicator","shell-version":["3.22"],"url":"http://git.gnome.org/gnome-shell-extensions","uuid":"workspace-indicator@gnome-shell-extensions.gcampax.github.com","version":31},"TopIcons@phocean.net":{"_generated":"Generated by SweetTooth, do not edit","description":"This extension moves legacy tray icons (bottom left of Gnome Shell) to the top panel. It is a fork from the original extension from ag  with settings for icon opacity, saturation, padding, size and tray position, along with a few minor fixes and integration with the Skype integration extension.","gettext-domain":"TopIcons-Plus","name":"TopIcons Plus","settings-schema":"org.gnome.shell.extensions.topicons","shell-version":["3.16","3.18","3.20","3.22","3.21.91"],"url":"https://github.com/phocean/TopIcons-plus","uuid":"TopIcons@phocean.net","version":18}}
`

Here's the response from the server:
```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at proxy02.gnome.org Port 443</address>
</body></html>
```

The failure on the client occurs when trying to parse the error markup into JSON:
```JS ERROR: SyntaxError: JSON.parse: unexpected character @ /home/jason/.local/share/gnome-shell/extensions/update-extensions@franglais125.gmail.com/extension.js:131```

Thanks!

**Comment by franglais125** [comment]
Hi!

Thanks for the feedback! I actually found the same problem as you, and broke down the "message" into smaller batches. The original extension used to send all the information in a single message, and I broke it down to batches of 10 extensions. I then realized even then it sometimes is too long.

I now use batches of 3 extensions only, I just submitted to e.g.o and it's awaiting review.

Do you mind testing the latest git version to see if it works? `make install`, as for dash-to-panel.

Cheers!

**Comment by jderose9** [comment]
I looked at the API code here:
https://github.com/GNOME/extensions-web/blob/master/sweettooth/extensions/views.py

In shell_update() it only seems to use the "version" parameter, so I think it is safe to only pass that.

I made a pull request #3.

**Comment by franglais125** [comment]
@jderose9 Sorry for the off-topic. I work on another extension (https://github.com/franglais125/apt-update-indicator) that looks for package updates. I am in the process of making it compatible with other distros as well, as for the moment it is apt-only.

Do you happen to use something like Fedora, Arch? This is the branch I'd like to merge, to support other distros: https://github.com/franglais125/apt-update-indicator/tree/pkcon_get_updates

I'd love it if you could give me some feedback. Sorry for the trouble!

**Comment by jderose9** [comment]
I am using Fedora 25. I installed your other extension and I get in some sort of an error state. There's nothing logged to the journal though. I didn't debug beyond that.

![screenshot from 2017-02-16 16-41-53](https://cloud.githubusercontent.com/assets/2118702/23050018/c7fa9902-f48d-11e6-88b9-f2de43a73d4e.png)


I'm guessing you know, but you can use Boxes to load up another distribution's iso in a virtual machine and test stuff on other distros pretty quickly.

**Comment by franglais125** [comment]
Hmm, did you install the specific branch https://github.com/franglais125/apt-update-indicator/tree/pkcon_get_updates ? The master is apt-only so far.

If you did, then I'll have to debug a bit more it seems.

And yeah, I run a few things in VM, but my testing can only go so far :)

**Comment by jderose9** [comment]
Yes. It is configured to use Gnome Software to update.. that's correct?

**Comment by franglais125** [comment]
Yes, Gnome Software should be fine for the update process.

But I'm wondering if it is *checking* for updates properly. However, nevermind, I don't want to waste your time. It will take some more work on my end.

The only thing I can think of is that you don't have packagekit installed, which is what I use to check for updates.
```
pkcon refresh
pkcon get-updates
```

Thanks!

**Comment by jderose9** [comment]
Actually, I was on the wrong branch. It is working. I see my package count with updates reflected properly. When I click "Apply Updates" it opens gnome software.

**Comment by franglais125** [comment]
Thanks a bunch :)
