### ISSUE TITLE
Open extension page from clock popup's notification list?

### ISSUE THREAD

**Issue by jderose9** [franglais125/update-extensions#4]
Is it possible to open extensions.gnome.org the way that I can from the toast popup by clicking on the notification in the list that pops up when clicking on the clock widget in the main panel?

Most notifications seem to take me to that application when clicking, but the notification from this extension is just dismissed when clicked. (Not actually sure this is possible in gnome since there is no application tied to the notification but rather an extension)

**Comment by franglais125** [comment]
Thanks for opening this issue. I'll look into it!

**Comment by franglais125** [comment]
I couldn't really find a way around that. In the old MessageTray, one could interact with old notifications, but it seems this is no longer possible.

Perhaps adding an indicator can help, although I don't really want to clutter the indicator area with yet-another-indicator.

**Comment by jderose9** [comment]
ok, I'll close this for now. thanks for checking!
